### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by braver** [braver/isotope-ui#36]
- [x] button status indicator
- [x] stretch button gradient and use darkest for active state
- [x] increase saturation for blueish themes
- [x] find out what's breaking style guide
- [x] decrease progress bar height
